/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import javax.swing.JOptionPane;
import App.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
/**
 *
 * @author marco
 */
public class AdministradorPanel extends javax.swing.JPanel {
    List<Tarea> tareas;
    List<Usuario> usuarios;
    DefaultListModel modeloLista;
    DefaultListModel modeloLista2;
    DefaultListModel modeloLista3;
    DefaultListModel modeloLista4;
    DefaultListModel modeloLista5;
    Admin admin;
    /**
     * Creates new form AdministradorPanel
     */
    public AdministradorPanel(Admin admin) {
        modeloLista3=new DefaultListModel();  
        this.admin=admin;
        usuarios=admin.getUsuarios();
        for(Usuario usuario:usuarios){
            modeloLista3.addElement(usuario.getNombre());
        }

        initComponents();
        actualizarListasTareas();
        selectorUsuarios.setModel(modeloLista3);
    }
    public void actualizarListasTareas(){
        modeloLista=new DefaultListModel(); 
        modeloLista2=new DefaultListModel();
        tareas=admin.getTareas();
        for(Tarea tarea:tareas){
            if(tarea.getEstado()!=3){
                modeloLista.addElement(tarea.getNombre());
            }
            else{
                modeloLista2.addElement(tarea.getNombre());
            }
        }
        selectorTareas.setModel(modeloLista);
        selectorTareasEntregadas.setModel(modeloLista2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectorTareas = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nombreTareaTexto = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        descripcionTexto = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        selectorTareasEntregadas = new javax.swing.JList<>();
        estadoComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        puestoUsuarioTexto = new javax.swing.JTextField();
        idUsuarioTexto = new javax.swing.JTextField();
        nombreUsuarioTexto = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        estadoTareaUsuario = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        descripcionTareaUsuario = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        nombreTareaUsuario = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        selectorUsuarios = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        selectorTareasPorEntregarUser = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        selectorTareasEntregadasUser = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectorTareas.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        selectorTareas.setSelectionBackground(new java.awt.Color(238, 112, 82));
        selectorTareas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                selectorTareasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(selectorTareas);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 190, 170));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 112, 82));
        jLabel5.setText("ESTADO:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(238, 112, 82));
        jLabel6.setText("TAREAS ENTREGADAS:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(238, 112, 82));
        jLabel7.setText("TAREA:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(238, 112, 82));
        jLabel8.setText("DESCRIPCION:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        nombreTareaTexto.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        nombreTareaTexto.setBorder(null);
        nombreTareaTexto.setEnabled(false);
        nombreTareaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTareaTextoActionPerformed(evt);
            }
        });
        jPanel3.add(nombreTareaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 360, 34));

        descripcionTexto.setColumns(20);
        descripcionTexto.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        descripcionTexto.setRows(5);
        descripcionTexto.setText("Descripción");
        descripcionTexto.setEnabled(false);
        jScrollPane3.setViewportView(descripcionTexto);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 360, 180));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(238, 112, 82));
        jLabel9.setText("TAREAS A REALIZAR:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 30));

        selectorTareasEntregadas.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        selectorTareasEntregadas.setSelectionBackground(new java.awt.Color(238, 112, 82));
        selectorTareasEntregadas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                selectorTareasEntregadasValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(selectorTareasEntregadas);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 190, 170));

        estadoComboBox.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En Progreso", "Terminada" }));
        estadoComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoComboBoxItemStateChanged(evt);
            }
        });
        estadoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoComboBoxActionPerformed(evt);
            }
        });
        jPanel3.add(estadoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 150, 30));

        jTabbedPane1.addTab("Tareas", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(238, 112, 82));
        jLabel10.setText("TAREAS POR ENTREGAR:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, 30));

        jButton1.setText("Nueva Tarea");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, 20));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(238, 112, 82));
        jLabel12.setText("USUARIOS:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(238, 112, 82));
        jLabel13.setText("ID:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(238, 112, 82));
        jLabel14.setText("NOMBRE:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 30));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(238, 112, 82));
        jLabel15.setText("PUESTO:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, 30));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(238, 112, 82));
        jLabel16.setText("TAREAS ENTREGADAS:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, 30));

        puestoUsuarioTexto.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        puestoUsuarioTexto.setBorder(null);
        puestoUsuarioTexto.setEnabled(false);
        puestoUsuarioTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoUsuarioTextoActionPerformed(evt);
            }
        });
        jPanel2.add(puestoUsuarioTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 190, 34));

        idUsuarioTexto.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        idUsuarioTexto.setBorder(null);
        idUsuarioTexto.setEnabled(false);
        idUsuarioTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idUsuarioTextoActionPerformed(evt);
            }
        });
        jPanel2.add(idUsuarioTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 190, 34));

        nombreUsuarioTexto.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        nombreUsuarioTexto.setBorder(null);
        nombreUsuarioTexto.setEnabled(false);
        nombreUsuarioTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioTextoActionPerformed(evt);
            }
        });
        jPanel2.add(nombreUsuarioTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 190, 34));

        jButton2.setText("Crear Usuario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(238, 112, 82));
        jLabel11.setText("ESTADO:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        estadoTareaUsuario.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        estadoTareaUsuario.setBorder(null);
        estadoTareaUsuario.setEnabled(false);
        estadoTareaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoTareaUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(estadoTareaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 230, 34));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(238, 112, 82));
        jLabel17.setText("DESCRIPCION:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        descripcionTareaUsuario.setColumns(20);
        descripcionTareaUsuario.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        descripcionTareaUsuario.setRows(5);
        descripcionTareaUsuario.setText("Descripción");
        descripcionTareaUsuario.setEnabled(false);
        jScrollPane7.setViewportView(descripcionTareaUsuario);

        jPanel2.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 360, 100));

        jButton3.setText("Dar por Entregada");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(238, 112, 82));
        jLabel18.setText("TAREA:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        nombreTareaUsuario.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        nombreTareaUsuario.setBorder(null);
        nombreTareaUsuario.setEnabled(false);
        nombreTareaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTareaUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(nombreTareaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 230, 34));

        selectorUsuarios.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        selectorUsuarios.setSelectionBackground(new java.awt.Color(238, 112, 82));
        selectorUsuarios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                selectorUsuariosValueChanged(evt);
            }
        });
        jScrollPane8.setViewportView(selectorUsuarios);

        jPanel2.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 190, 170));

        selectorTareasPorEntregarUser.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        selectorTareasPorEntregarUser.setSelectionBackground(new java.awt.Color(238, 112, 82));
        selectorTareasPorEntregarUser.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                selectorTareasPorEntregarUserValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(selectorTareasPorEntregarUser);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 190, 150));

        selectorTareasEntregadasUser.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        selectorTareasEntregadasUser.setSelectionBackground(new java.awt.Color(238, 112, 82));
        selectorTareasEntregadasUser.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                selectorTareasEntregadasUserValueChanged(evt);
            }
        });
        jScrollPane9.setViewportView(selectorTareasEntregadasUser);

        jPanel2.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 190, 150));

        jButton4.setText("Eliminar Usuario");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        jTabbedPane1.addTab("Usuarios", jPanel2);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTareaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTareaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTareaTextoActionPerformed

    private void selectorTareasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_selectorTareasValueChanged
        selectorTareasEntregadas.clearSelection();
        try{
        List<Tarea> tareasPorEntregar=new ArrayList<>();
        for(Tarea tarea:tareas){
            if(tarea.getEstado()!=3){
                tareasPorEntregar.add(tarea);
            }
        }
        
            nombreTareaTexto.setText(tareasPorEntregar.get(selectorTareas.getSelectedIndex()).getNombre());
            descripcionTexto.setText(tareasPorEntregar.get(selectorTareas.getSelectedIndex()).getDescripcion());
            estadoComboBox.setVisible(true);
            jLabel5.setVisible(true);
            this.validate();
            estadoComboBox.setSelectedIndex(tareasPorEntregar.get(selectorTareas.getSelectedIndex()).getEstado());
        }catch(Exception e){
            
        }
        
        
    }//GEN-LAST:event_selectorTareasValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombreTarea = JOptionPane.showInputDialog ("Nombre de la Tarea: ");
        JTextArea textArea = new JTextArea("Ingrese Descripcion");
        textArea.setColumns(30);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        textArea.setSize(textArea.getPreferredSize().width, 2);
        JOptionPane.showMessageDialog(null, new JScrollPane(textArea), "Descripcion",JOptionPane.OK_CANCEL_OPTION,null);
        String describcionTarea=textArea.getText();
        Tarea nuevaTarea=new Tarea(nombreTarea,describcionTarea);
        Usuario usuarioActualizado=admin.getUsuarios().get(selectorUsuarios.getSelectedIndex());
        usuarioActualizado.getTareas().add(nuevaTarea);
        admin.modificarUsuario(admin.indexOfUsuarios(usuarioActualizado), usuarioActualizado);
        usuarios=admin.getUsuarios();
        List<Tarea> tareasUsuario=usuarios.get(selectorUsuarios.getSelectedIndex()).getTareas();
        modeloLista4=new DefaultListModel(); 
        modeloLista5=new DefaultListModel();
        for(Tarea tarea:tareasUsuario){
            if(tarea.getEstado()==3){
                modeloLista4.addElement(tarea.getNombre());
            }else{
                modeloLista5.addElement(tarea.getNombre());
            }
        }
        
        selectorTareasPorEntregarUser.setModel(modeloLista5);
        selectorTareasPorEntregarUser.setSelectedIndex(0);
        selectorTareasEntregadasUser.setModel(modeloLista4);
        selectorTareas.clearSelection();
        selectorTareasEntregadas.clearSelection();
        actualizarListasTareas();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void puestoUsuarioTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoUsuarioTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoUsuarioTextoActionPerformed

    private void idUsuarioTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idUsuarioTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idUsuarioTextoActionPerformed

    private void nombreUsuarioTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioTextoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JCheckBox checkbox = new JCheckBox("Permisos de Administrador");
        JOptionPane.showMessageDialog(null,checkbox,"Crear Usuario",JOptionPane.PLAIN_MESSAGE);
        String idUsuario = JOptionPane.showInputDialog ("ID del Usuario: ");
        String nombreUsuario = JOptionPane.showInputDialog ("Nombre del Usuario: ");
        String puestoUsuario = JOptionPane.showInputDialog ("Puesto del Usuario: ");
        String usuarioUsuario = JOptionPane.showInputDialog ("Usuario: ");
        String passwordUsuario = JOptionPane.showInputDialog ("Password: ");
        if(!idUsuario.equals("")&&!nombreUsuario.equals("")&&!puestoUsuario.equals("")&&!usuarioUsuario.equals("")&&!passwordUsuario.equals("")){
            if(checkbox.isEnabled()){
                Admin nuevoAdmin=new Admin(idUsuario,nombreUsuario,puestoUsuario,usuarioUsuario,passwordUsuario);
            }else{
                Usuario nuevoUsuario=new Usuario(idUsuario,nombreUsuario,puestoUsuario,usuarioUsuario,passwordUsuario);
                admin.crearUsuario(nuevoUsuario);
            }
            usuarios=admin.getUsuarios();
            modeloLista3=new DefaultListModel();  
            for(Usuario usuario:usuarios){
                modeloLista3.addElement(usuario.getNombre());
            }
            selectorUsuarios.setModel(modeloLista3);
            selectorUsuarios.setSelectedIndex(0);
            }
        else{
            JOptionPane.showMessageDialog(null,"Debe llenar todos los campos");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void estadoTareaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoTareaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoTareaUsuarioActionPerformed

    private void nombreTareaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTareaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTareaUsuarioActionPerformed

    private void selectorUsuariosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_selectorUsuariosValueChanged
        try{
        idUsuarioTexto.setText(usuarios.get(selectorUsuarios.getSelectedIndex()).getId());
        nombreUsuarioTexto.setText(usuarios.get(selectorUsuarios.getSelectedIndex()).getNombre());
        puestoUsuarioTexto.setText(usuarios.get(selectorUsuarios.getSelectedIndex()).getPuesto());
        List<Tarea> tareasUsuario=usuarios.get(selectorUsuarios.getSelectedIndex()).getTareas();
        modeloLista4=new DefaultListModel(); 
        modeloLista5=new DefaultListModel();
        for(Tarea tarea:tareasUsuario){
            if(tarea.getEstado()==3){
                modeloLista4.addElement(tarea.getNombre());
            }else{
                modeloLista5.addElement(tarea.getNombre());
            }
        }
        selectorTareasPorEntregarUser.setModel(modeloLista5);
        selectorTareasEntregadasUser.setModel(modeloLista4);
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_selectorUsuariosValueChanged

    private void selectorTareasEntregadasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_selectorTareasEntregadasValueChanged
        selectorTareas.clearSelection();
        try{
        List<Tarea> tareasEntregadas=new ArrayList<>();
        for(Tarea tarea:tareas){
            if(tarea.getEstado()==3){
                tareasEntregadas.add(tarea);
            }
        }
        nombreTareaTexto.setText(tareasEntregadas.get(selectorTareasEntregadas.getSelectedIndex()).getNombre());
        descripcionTexto.setText(tareasEntregadas.get(selectorTareasEntregadas.getSelectedIndex()).getDescripcion());
        estadoComboBox.setVisible(false);
        jLabel5.setVisible(false);
        this.validate();
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_selectorTareasEntregadasValueChanged

    private void estadoComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_estadoComboBoxItemStateChanged
        Admin adminActualizado=admin;
        List<Tarea> tareasPorEntregar=new ArrayList<>();
        for(Tarea tarea:tareas){
            if(tarea.getEstado()!=3){
                tareasPorEntregar.add(tarea);
            }
        }
        adminActualizado.setEstado(tareas.indexOf(tareasPorEntregar.get(selectorTareas.getSelectedIndex())), estadoComboBox.getSelectedIndex());
        admin=adminActualizado;
        admin.modificarUsuario(admin.indexOfUsuarios(admin), admin);
        modeloLista3=new DefaultListModel();  
        usuarios=admin.getUsuarios();
        for(Usuario usuario:usuarios){
            modeloLista3.addElement(usuario.getNombre());
        }
        selectorTareasPorEntregarUser.clearSelection();
        selectorTareasEntregadasUser.clearSelection();
        selectorUsuarios.clearSelection();
        selectorUsuarios.setModel(modeloLista3);
        
    }//GEN-LAST:event_estadoComboBoxItemStateChanged

    private void estadoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoComboBoxActionPerformed
        
    }//GEN-LAST:event_estadoComboBoxActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        selectorTareasPorEntregarUser.clearSelection();
        selectorTareasEntregadasUser.clearSelection();
        admin.eliminarUsuario(selectorUsuarios.getSelectedIndex());
        usuarios=admin.getUsuarios();
        modeloLista3=new DefaultListModel();  
        for(Usuario usuario:usuarios){
            modeloLista3.addElement(usuario.getNombre());
        }
        selectorUsuarios.setModel(modeloLista3);
        selectorUsuarios.setSelectedIndex(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void selectorTareasPorEntregarUserValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_selectorTareasPorEntregarUserValueChanged
        selectorTareasEntregadasUser.clearSelection();
        try{
        List<Tarea> tareasUsuario=usuarios.get(selectorUsuarios.getSelectedIndex()).getTareas();
        List<Tarea> tareasPorEntregar=new ArrayList<>();
        for(Tarea tarea:tareasUsuario){
            if(tarea.getEstado()!=3){
                tareasPorEntregar.add(tarea);
            }
        }
        nombreTareaUsuario.setText(tareasPorEntregar.get(selectorTareasPorEntregarUser.getSelectedIndex()).getNombre());
        descripcionTareaUsuario.setText(tareasPorEntregar.get(selectorTareasPorEntregarUser.getSelectedIndex()).getDescripcion());
        int estado=tareasPorEntregar.get(selectorTareasPorEntregarUser.getSelectedIndex()).getEstado();
        switch(estado){
            case 0:
                estadoTareaUsuario.setText("Pendiente");
                break;
            case 1:
                estadoTareaUsuario.setText("En Proceso");
                break;
            case 2:
                estadoTareaUsuario.setText("Terminada");
                break; 
        }
        jButton3.setEnabled(true);
        }catch(Exception e){
            nombreTareaUsuario.setText("");
            descripcionTareaUsuario.setText("Descripcion");
            estadoTareaUsuario.setText("");
        }
    }//GEN-LAST:event_selectorTareasPorEntregarUserValueChanged

    private void selectorTareasEntregadasUserValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_selectorTareasEntregadasUserValueChanged
        selectorTareasPorEntregarUser.clearSelection();
        try{
        List<Tarea> tareasUsuario=usuarios.get(selectorUsuarios.getSelectedIndex()).getTareas();
        List<Tarea> tareasEntregadas=new ArrayList<>();
        for(Tarea tarea:tareasUsuario){
            if(tarea.getEstado()==3){
                tareasEntregadas.add(tarea);
            }
        }
        nombreTareaUsuario.setText(tareasEntregadas.get(selectorTareasEntregadasUser.getSelectedIndex()).getNombre());
        descripcionTareaUsuario.setText(tareasEntregadas.get(selectorTareasEntregadasUser.getSelectedIndex()).getDescripcion());
        estadoTareaUsuario.setText("Entregada");
        jButton3.setEnabled(false);
        }catch(Exception e){
            nombreTareaUsuario.setText("");
            descripcionTareaUsuario.setText("Descripcion");
            estadoTareaUsuario.setText("");
        }
        
    }//GEN-LAST:event_selectorTareasEntregadasUserValueChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Usuario usuarioActualizado=usuarios.get(selectorUsuarios.getSelectedIndex());
        List<Tarea> tareasUsuario=usuarios.get(selectorUsuarios.getSelectedIndex()).getTareas();
        List<Tarea> tareasPorEntregar=new ArrayList<>();
        for(Tarea tarea:tareasUsuario){
            if(tarea.getEstado()!=3){
                tareasPorEntregar.add(tarea);
            }
        }
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea marcar esta tarea como entregada?","Tarea Entregada",dialog);
        if(result==0){
            usuarioActualizado.setEstado(tareasUsuario.indexOf(tareasPorEntregar.get(selectorTareas.getSelectedIndex())), 3);
            usuarios.set(admin.indexOfUsuarios(usuarioActualizado),usuarioActualizado);
            admin.modificarUsuario(admin.indexOfUsuarios(usuarioActualizado), usuarioActualizado);
            modeloLista4=new DefaultListModel(); 
            modeloLista5=new DefaultListModel();
            for(Tarea tarea:tareasUsuario){
                if(tarea.getEstado()==3){
                    modeloLista4.addElement(tarea.getNombre());
                }else{
                    modeloLista5.addElement(tarea.getNombre());
                }
            }
            selectorTareasPorEntregarUser.setModel(modeloLista5);
            selectorTareasEntregadasUser.setModel(modeloLista4);
            
        }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descripcionTareaUsuario;
    private javax.swing.JTextArea descripcionTexto;
    private javax.swing.JComboBox<String> estadoComboBox;
    private javax.swing.JTextField estadoTareaUsuario;
    private javax.swing.JTextField idUsuarioTexto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nombreTareaTexto;
    private javax.swing.JTextField nombreTareaUsuario;
    private javax.swing.JTextField nombreUsuarioTexto;
    private javax.swing.JTextField puestoUsuarioTexto;
    private javax.swing.JList<String> selectorTareas;
    private javax.swing.JList<String> selectorTareasEntregadas;
    private javax.swing.JList<String> selectorTareasEntregadasUser;
    private javax.swing.JList<String> selectorTareasPorEntregarUser;
    private javax.swing.JList<String> selectorUsuarios;
    // End of variables declaration//GEN-END:variables
}
