/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;
import App.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author marco
 */
public class UserPanel extends javax.swing.JPanel {
    Usuario usuarioActual;
    Admin admin;
    List<Tarea> tareas;
    DefaultListModel modeloLista;
    DefaultListModel modeloLista2;
    /**
     * Creates new form UserPanel
     */
    public UserPanel(Usuario usuarioActual,Admin admin) {
        this.usuarioActual=usuarioActual;
        this.admin=admin;
        initComponents();
        actualizarListasTareas();
    }
    public void actualizarListasTareas(){
        modeloLista=new DefaultListModel(); 
        modeloLista2=new DefaultListModel();
        tareas=usuarioActual.getTareas();
        for(Tarea tarea:tareas){
            if(tarea.getEstado()!=3){
                modeloLista.addElement(tarea.getNombre());
            }
            else{
                modeloLista2.addElement(tarea.getNombre());
            }
        }
        selectorTareas.setModel(modeloLista);
        selectorTareasEntregadas.setModel(modeloLista2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        selectorTareas = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        estadoComboBox = new javax.swing.JComboBox<>();
        nombreTareaTexto = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        descripcionTexto = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectorTareasEntregadas = new javax.swing.JList<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectorTareas.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        selectorTareas.setSelectionBackground(new java.awt.Color(238, 112, 82));
        selectorTareas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                selectorTareasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(selectorTareas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 190, 170));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 112, 82));
        jLabel5.setText("ESTADO:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(238, 112, 82));
        jLabel6.setText("TAREAS ENTREGADAS:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(238, 112, 82));
        jLabel7.setText("TAREA:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(238, 112, 82));
        jLabel8.setText("DESCRIPCION:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        estadoComboBox.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En Progreso", "Terminada", " " }));
        estadoComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estadoComboBoxItemStateChanged(evt);
            }
        });
        estadoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoComboBoxActionPerformed(evt);
            }
        });
        add(estadoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 150, 30));

        nombreTareaTexto.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        nombreTareaTexto.setBorder(null);
        nombreTareaTexto.setEnabled(false);
        nombreTareaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTareaTextoActionPerformed(evt);
            }
        });
        add(nombreTareaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 360, 34));

        descripcionTexto.setColumns(20);
        descripcionTexto.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        descripcionTexto.setRows(5);
        descripcionTexto.setText("Descripción");
        descripcionTexto.setEnabled(false);
        jScrollPane3.setViewportView(descripcionTexto);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 360, 180));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(238, 112, 82));
        jLabel9.setText("TAREAS A REALIZAR:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, 40));

        selectorTareasEntregadas.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        selectorTareasEntregadas.setSelectionBackground(new java.awt.Color(238, 112, 82));
        selectorTareasEntregadas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                selectorTareasEntregadasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(selectorTareasEntregadas);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 190, 170));
    }// </editor-fold>//GEN-END:initComponents

    private void estadoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoComboBoxActionPerformed
        
    }//GEN-LAST:event_estadoComboBoxActionPerformed

    private void nombreTareaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTareaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTareaTextoActionPerformed

    private void selectorTareasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_selectorTareasValueChanged
        selectorTareasEntregadas.clearSelection();
        try{
        List<Tarea> tareasPorEntregar=new ArrayList<>();
        for(Tarea tarea:tareas){
            if(tarea.getEstado()!=3){
                tareasPorEntregar.add(tarea);
            }
        }
        
            nombreTareaTexto.setText(tareasPorEntregar.get(selectorTareas.getSelectedIndex()).getNombre());
            descripcionTexto.setText(tareasPorEntregar.get(selectorTareas.getSelectedIndex()).getDescripcion());
            estadoComboBox.setVisible(true);
            jLabel5.setVisible(true);
            this.validate();
            estadoComboBox.setSelectedIndex(tareasPorEntregar.get(selectorTareas.getSelectedIndex()).getEstado());
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_selectorTareasValueChanged

    private void estadoComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_estadoComboBoxItemStateChanged
       Usuario usuarioActualizado=usuarioActual;
        List<Tarea> tareasPorEntregar=new ArrayList<>();
        for(Tarea tarea:tareas){
            if(tarea.getEstado()!=3){
                tareasPorEntregar.add(tarea);
            }
        }
        usuarioActualizado.setEstado(tareas.indexOf(tareasPorEntregar.get(selectorTareas.getSelectedIndex())), estadoComboBox.getSelectedIndex());
        usuarioActual=usuarioActualizado;
        admin.modificarUsuario(admin.indexOfUsuarios(usuarioActual), usuarioActual);
    }//GEN-LAST:event_estadoComboBoxItemStateChanged

    private void selectorTareasEntregadasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_selectorTareasEntregadasValueChanged
        selectorTareas.clearSelection();
        try{
        List<Tarea> tareasEntregadas=new ArrayList<>();
        for(Tarea tarea:tareas){
            if(tarea.getEstado()==3){
                tareasEntregadas.add(tarea);
            }
        }
        nombreTareaTexto.setText(tareasEntregadas.get(selectorTareasEntregadas.getSelectedIndex()).getNombre());
        descripcionTexto.setText(tareasEntregadas.get(selectorTareasEntregadas.getSelectedIndex()).getDescripcion());
        estadoComboBox.setVisible(false);
        jLabel5.setVisible(false);
        this.validate();
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_selectorTareasEntregadasValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descripcionTexto;
    private javax.swing.JComboBox<String> estadoComboBox;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nombreTareaTexto;
    private javax.swing.JList<String> selectorTareas;
    private javax.swing.JList<String> selectorTareasEntregadas;
    // End of variables declaration//GEN-END:variables
}
